---
abstract: 'An XML->XSL transform custom field, and Arcsight event data extraction from XML.'
author:
  - 'Richard Harman C<< <richard+RTx-XMLXSLTCF@richardharman.com> >>'
  - 'Richard G Harman Jr <richard+RTx-XMLXSLTCF@richardharman.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RTx-XMLXSLTCF
no_index:
  directory:
    - etc
    - html
    - inc
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.0.1
